"use client";

import { useEffect, useRef } from "react";
import { useSession } from "next-auth/react";
import { signInWithCustomToken } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { logger } from "@/lib/logger";

/**
 * Firebase Auth Provider
 *
 * Bridges NextAuth session with Firebase Authentication.
 * Uses the custom token generated by NextAuth to sign into Firebase Client SDK.
 * This ensures Firestore rules (request.auth) work correctly for real-time
 * listeners (onSnapshot) used in the chat system.
 *
 * Fix: tracks lastSignedInToken so token rotations cause a fresh sign-in
 * instead of being silently skipped by the old retryRef guard.
 */
export function FirebaseAuthProvider({ children }: { children: React.ReactNode }) {
    const { data: session } = useSession();
    // Track which token version we last successfully signed in with.
    // This ensures we re-sign when NextAuth refreshes/rotates the custom token.
    const lastSignedInTokenRef = useRef<string | null>(null);
    const inProgressRef = useRef(false);

    useEffect(() => {
        const token = session?.firebaseToken;
        if (!token) return;
        // Skip if we already signed in with this exact token value
        if (lastSignedInTokenRef.current === token) return;
        // Skip if a sign-in attempt is already in flight
        if (inProgressRef.current) return;

        inProgressRef.current = true;

        const MAX_RETRIES = 3;
        let attempt = 0;

        async function trySignIn() {
            while (attempt < MAX_RETRIES) {
                try {
                    const userCredential = await signInWithCustomToken(auth, token!);
                    lastSignedInTokenRef.current = token!; // mark as done for this token
                    logger.debug("Firebase Auth: Signed in via custom token", {
                        uid: userCredential.user.uid,
                        attempt: attempt + 1,
                    });
                    return;
                } catch (error: any) {
                    attempt++;
                    if (attempt < MAX_RETRIES && error?.code === "auth/network-request-failed") {
                        const delay = Math.min(1000 * Math.pow(2, attempt - 1), 4000);
                        logger.warn(`Firebase Auth: Retry ${attempt}/${MAX_RETRIES} after ${delay}ms`, { error: error.message });
                        await new Promise(r => setTimeout(r, delay));
                    } else {
                        logger.error("Firebase Auth: Failed to sign in with custom token", { error: error.message, attempt });
                        return;
                    }
                }
            }
        }

        trySignIn().finally(() => { inProgressRef.current = false; });
    }, [session?.firebaseToken]);

    return <>{children}</>;
}
