"use client";

import { useEffect } from "react";
import { useSession } from "next-auth/react";
import { signInWithCustomToken } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { logger } from "@/lib/logger";

/**
 * Firebase Auth Provider
 * 
 * Bridges NextAuth session with Firebase Authentication.
 * Uses the custom token generated by NextAuth to sign into Firebase Client SDK.
 * This ensures Firestore rules (request.auth) work correctly.
 */
export function FirebaseAuthProvider({ children }: { children: React.ReactNode }) {
    const { data: session } = useSession();

    useEffect(() => {
        if (session?.firebaseToken) {
            signInWithCustomToken(auth, session.firebaseToken)
                .then((userCredential) => {
                    logger.debug("Firebase Auth: Signed in via custom token", {
                        uid: userCredential.user.uid
                    });
                })
                .catch((error) => {
                    logger.error("Firebase Auth: Failed to sign in with custom token", error);
                });
        }
    }, [session?.firebaseToken]);

    return <>{children}</>;
}
