"use client";

import { useEffect, useRef } from "react";
import { useSession } from "next-auth/react";
import { signInWithCustomToken } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { logger } from "@/lib/logger";

/**
 * Firebase Auth Provider
 * 
 * Bridges NextAuth session with Firebase Authentication.
 * Uses the custom token generated by NextAuth to sign into Firebase Client SDK.
 * This ensures Firestore rules (request.auth) work correctly.
 * 
 * Includes retry logic for transient network errors (ERR_CONNECTION_CLOSED).
 */
export function FirebaseAuthProvider({ children }: { children: React.ReactNode }) {
    const { data: session } = useSession();
    const retryRef = useRef(false);

    useEffect(() => {
        if (!session?.firebaseToken) return;
        if (retryRef.current) return; // Already in progress
        retryRef.current = true;

        const MAX_RETRIES = 3;
        let attempt = 0;

        async function trySignIn() {
            while (attempt < MAX_RETRIES) {
                try {
                    const userCredential = await signInWithCustomToken(auth, session!.firebaseToken!);
                    logger.debug("Firebase Auth: Signed in via custom token", {
                        uid: userCredential.user.uid,
                        attempt: attempt + 1,
                    });
                    return; // Success
                } catch (error: any) {
                    attempt++;
                    if (attempt < MAX_RETRIES && error?.code === "auth/network-request-failed") {
                        const delay = Math.min(1000 * Math.pow(2, attempt - 1), 4000);
                        logger.warn(`Firebase Auth: Retry ${attempt}/${MAX_RETRIES} after ${delay}ms`, { error: error.message });
                        await new Promise(r => setTimeout(r, delay));
                    } else {
                        logger.error("Firebase Auth: Failed to sign in with custom token", { error: error.message, attempt });
                        return;
                    }
                }
            }
        }

        trySignIn().finally(() => { retryRef.current = false; });
    }, [session?.firebaseToken]);

    return <>{children}</>;
}

