#!/usr/bin/env bash
#
# Run the ENTIRE app locally against a LOCAL database — one command.
#
#   npm run dev:local
#
# WHY THIS EXISTS
# ---------------
# Local development has always talked to the production database: .env.local
# and .env.production.local point at the same Supabase project (recorded in
# migration 004's notes). "Testing locally" therefore meant testing on
# production with a localhost front end — which is how test writes, seed
# attempts and experiments have been reaching live customer data.
#
# This script gives local work its own database:
#
#   1. Boots a full local Supabase (Postgres + PostgREST + Kong + GoTrue) via
#      scripts/ci-integration-db.sh — the SAME script CI uses, so local and CI
#      cannot drift. Schema first, then every migration, RLS included.
#   2. Writes the stack's credentials to .env.development.local. In Next.js
#      dev, that file OUTRANKS .env.local — so the dev server reads the local
#      database while .env.local (production) sits untouched underneath.
#   3. Seeds the e2e fixtures (scripts/seed-local.ts, which refuses to run
#      against anything that is not localhost).
#   4. Starts `npm run dev` — unless SKIP_DEV=1, for CI or for running the
#      Playwright suite instead, which boots its own server.
#
# REQUIREMENTS: Docker running. First boot downloads images (a few minutes).
#
# TO GO BACK to production-pointing dev (not recommended): delete
# .env.development.local. Its absence is what re-exposes .env.local.

set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! docker info >/dev/null 2>&1; then
    echo "❌ Docker is not running. Start Docker Desktop (or the docker daemon) and retry." >&2
    exit 1
fi

echo "== Booting local Supabase (schema + all migrations, RLS included)…"
STACK_OUT="$(mktemp)"
./scripts/ci-integration-db.sh | tee "$STACK_OUT"

# The script prints `export KEY=VALUE` lines when not under GitHub Actions.
eval "$(grep -E '^export (NEXT_PUBLIC_SUPABASE_URL|NEXT_PUBLIC_SUPABASE_ANON_KEY|SUPABASE_SERVICE_ROLE_KEY)=' "$STACK_OUT")"
rm -f "$STACK_OUT"

if [ -z "${NEXT_PUBLIC_SUPABASE_URL:-}" ]; then
    echo "❌ Local stack started but no credentials were captured — see output above." >&2
    exit 1
fi

# Refuse to write a "local" env file that points anywhere non-local. This can
# only happen if ci-integration-db.sh changes shape; fail loudly rather than
# silently aim the dev server at a remote database.
case "$NEXT_PUBLIC_SUPABASE_URL" in
    http://localhost:*|http://127.0.0.1:*) ;;
    *) echo "❌ Captured URL is not local: $NEXT_PUBLIC_SUPABASE_URL" >&2; exit 1 ;;
esac

cat > .env.development.local <<EOF
# Generated by scripts/dev-local.sh — points the dev server at the LOCAL
# Supabase stack. This file outranks .env.local in \`next dev\`, which is the
# entire mechanism keeping local work off the production database.
# Delete this file to fall back to .env.local. Regenerate: npm run dev:local
NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF
echo "== Wrote .env.development.local (local stack now outranks .env.local)"

echo "== Seeding e2e fixtures…"
npx tsx scripts/seed-local.ts

if [ "${SKIP_DEV:-0}" = "1" ]; then
    echo "== SKIP_DEV=1 — stack is up and seeded. Run 'npm run dev' or 'npm run test:e2e' when ready."
else
    echo "== Starting dev server against the LOCAL database…"
    exec npm run dev
fi
