#!/bin/bash
echo "Opening Firebase Console Index pages..."
sleep 1
open "https://console.firebase.google.com/v1/r/project/easy-sales-hub/firestore/indexes?create_composite=ClNwcm9qZWN0cy9lYXN5LXNhbGVzLWh1Yi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdHJhbnNhY3Rpb25zL2luZGV4ZXMvXxABGgoKBnN0YXR1cxABGgoKBmFtb3VudBABGgwKCF9fbmFtZV9fEAE"
sleep 1
open "https://console.firebase.google.com/v1/r/project/easy-sales-hub/firestore/indexes?create_composite=ClNwcm9qZWN0cy9lYXN5LXNhbGVzLWh1Yi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdHJhbnNhY3Rpb25zL2luZGV4ZXMvXxABGgoKBnN0YXR1cxABGggKBGRhdGUQARoKCgZhbW91bnQQARoMCghfX25hbWVfXxAB"
sleep 1
open "https://console.firebase.google.com/v1/r/project/easy-sales-hub/firestore/indexes?create_composite=Clpwcm9qZWN0cy9lYXN5LXNhbGVzLWh1Yi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvY29vcGVyYXRpdmVfbWVtYmVycy9pbmRleGVzL18QARoRCg1wYXltZW50U3RhdHVzEAEaEwoPcmVnaXN0cmF0aW9uRmVlEAEaDAoIX19uYW1lX18QAQ"
sleep 1
open "https://console.firebase.google.com/v1/r/project/easy-sales-hub/firestore/indexes?create_composite=Clpwcm9qZWN0cy9lYXN5LXNhbGVzLWh1Yi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvd2l0aGRyYXdhbF9yZXF1ZXN0cy9pbmRleGVzL18QARoKCgZzdGF0dXMQARoKCgZhbW91bnQQARoMCghfX25hbWVfXxAB"
sleep 1
open "https://console.firebase.google.com/v1/r/project/easy-sales-hub/firestore/indexes?create_composite=Cldwcm9qZWN0cy9lYXN5LXNhbGVzLWh1Yi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvd2F2ZV93aXRoZHJhd2Fscy9pbmRleGVzL18QARoKCgZzdGF0dXMQARoKCgZhbW91bnQQARoMCghfX25hbWVfXxAB"

echo "Done! Please click 'Create' on all 5 opened browser tabs."
