-- Fabricated payment rows in the ledger — READ ONLY. No writes, updates or deletes.
--
-- PASTE INTO THE SUPABASE SQL EDITOR AND RUN. Returns one table.
--
-- ─────────────────────────────────────────────────────────────────────────────
--  WHY THIS EXISTS
--
--  The Academy population audit turned up a learner holding a paid place on
--  this evidence:
--
--      academyuser02@gmail.com    ₦50,000    ref TEST_E2E_REF_123456
--
--  Nobody paid that. It is the exact output of a mock that used to sit at the
--  top of verifyPaystackPayment in lib/paystack-server.ts:
--
--      const isTestRef = reference.startsWith('TEST_E2E_REF_') ||
--                        reference.startsWith('T') ||
--                        reference.startsWith('E2E_') ||
--                        reference === 'INVALID_REF' ||
--                        process.env.NODE_ENV === 'test' ||
--                        process.env.PLAYWRIGHT_TEST === 'true';
--
--  which returned, without contacting Paystack, a success for 5,000,000 kobo —
--  ₦50,000 — with type `academy_registration` and the CALLER'S OWN session id
--  echoed back as metadata.userId, so every "does this payment belong to you"
--  check compared the caller against themselves.
--
--  Two facts make that reach production rather than stay in a test run:
--
--    · e2e/helpers/auth.ts logged in as REAL PRODUCTION ACCOUNTS with their
--      real passwords — `academyuser02@gmail.com` among the five — and its own
--      header records that the suite "could only ever pass against production,
--      because those accounts exist nowhere else".
--
--    · tests/e2e/payment-callback.spec.ts sends `TEST_E2E_REF_123456`.
--
--  So the suite ran the payment callback against the live database as a live
--  user, the mock fabricated the success, and the row was written for keeps.
--
--  BOTH HALVES ARE ALREADY FIXED — the mock was removed in cc50b3b8
--  (2026-09-16) and the personas are seeded local identities now. WHAT WAS
--  NEVER CLEANED UP IS THE RESIDUE: rows already in the ledger. They matter
--  more than they did last week, because checkModuleAccess now reads
--  processed_payments as proof of payment. A fabricated row is now an
--  entitlement.
--
--  And the mock served EVERY verify path, not Academy's — cooperative
--  registration and contribution, wave, export investment, marketplace escrow,
--  farm-nation purchase. This query looks at the whole ledger.
--
-- ── WHAT THIS CAN AND CANNOT SETTLE ─────────────────────────────────────────
--
--  Section 1 is proof. Those reference shapes have no innocent explanation.
--
--  Section 2 IS NOT PROOF EITHER WAY, and that is the trap. Paystack really
--  does issue references of the form T + fifteen digits, and production carries
--  genuine ones — T457550806738035, T232223621495674, T750250345181632, all on
--  cooperative membership records. `startsWith('T')` caught those too. So a
--  T-reference is ambiguous by construction and cannot be judged from this
--  database at all.
--
--  THE ONLY AUTHORITY IS PAYSTACK. Export the transaction list from the
--  Paystack dashboard for the period and anti-join it on reference: a
--  reference Paystack has never heard of was never paid, whatever this table
--  says. Everything below narrows down what to check — it does not replace the
--  check.
--
--  NOTHING IS DELETED HERE. A fabricated row may sit under a real fulfilment
--  somebody has been using for months, and revoking it is a decision about a
--  person, not a row.
--
-- ── COLUMNS ────────────────────────────────────────────────────────────────
--
--  Per NATIVE_COLUMNS, on processed_payments:
--      id, user_id, amount, reference, created_at, updated_at   are NATIVE
--      type AND status live in raw_data                          <-- easy to miss
--
--  A filter written as `p.status = 'completed'` matches nothing.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────────────
--  WHY THIS IS NOW ONE UNBROKEN STATEMENT.
--
--  THE OWNER, pasting this file into the Supabase SQL Editor:
--
--      Failed to run sql query: ERROR: 42601: syntax error at or near ")"
--      LINE 42: ) x
--
--  This file used to be five sections separated by blank lines, and its own
--  header called that "correct and readable" because it was written for
--  `psql -f`. The editor splits on blank lines: it cut the query into
--  SEVENTEEN fragments and handed PostgreSQL one that began in the middle of
--  a UNION and ended at `) x`. Each fragment is a syntax error on its own.
--
--  That is #910 exactly, and #910's ratchet deliberately did not cover this
--  file -- the exclusion was argued from where the script was MEANT to run
--  rather than from where it IS run. Production is reachable through the
--  Supabase editor and not through psql, so the editor was always the real
--  client. The readable layout was protecting a workflow nobody has.
--
--  So the sections are now one statement with no blank line inside it, the
--  naira sign and em dashes are gone from the literals (ASCII only, for the
--  reason #910 records), and the file is in EDITOR_SCRIPTS with the rest.
--  Nothing about WHAT it asks has changed -- the five sections, their
--  filters and their labels are the same.
--
--  It still runs under `psql -f` exactly as before. One statement is valid
--  there too; only the line breaks moved.
-- ─────────────────────────────────────────────────────────────────────────────
with payments as (select p.id, p.user_id, p.reference, p.amount, p.created_at, coalesce(p.raw_data->>'type', '(none)') as ptype, coalesce(p.raw_data->>'status', '(none)') as pstatus, coalesce(p.amount in (50000, 5000000), false) as mock_amount, coalesce(p.created_at < date '2026-09-16', true) as predates_fix from processed_payments p)
select * from (
select 1 as sort, 'FABRICATED - reference shape is test-only' as section, ptype || '  |  NGN ' || coalesce(amount::text, '?') || '  |  ' || coalesce(reference, '(no reference)') as label, count(*)::bigint as rows_found from payments where reference = 'INVALID_REF' or reference like 'E2E\_%' or reference like 'TEST\_E2E\_REF\_%' group by 3
union all
select 2, 'T-REFERENCE - check these against the Paystack dashboard', case when reference ~ '^T[0-9]{15}$' and mock_amount then 'Paystack T-shape, but NGN 50,000 exactly  <-- check first' when reference ~ '^T[0-9]{15}$' then 'Paystack T-shape, amount is not the mock''s' when reference ~ '^T[0-9]{13}$' then 'T + 13 digits - a Date.now() timestamp; see section 5' else 'starts with T but NOT Paystack''s shape  <-- check first' end, count(*)::bigint from payments where reference like 'T%' and predates_fix and reference not like 'TEST\_E2E\_REF\_%' and reference not like 'E2E\_%' and reference <> 'INVALID_REF' group by 3
union all
select 3, 'EXACTLY NGN 50,000 AND OLDER THAN THE FIX, BY TYPE', ptype || '  (' || pstatus || ')', count(*)::bigint from payments where mock_amount and predates_fix group by 3
union all
select 4, 'ACADEMY PAYMENT ROWS IN FULL', coalesce(to_char(created_at, 'YYYY-MM-DD'), '(undated)') || '  |  NGN ' || coalesce(amount::text, '?') || '  |  ' || coalesce(reference, '(no reference)') || '  |  ' || pstatus, count(*)::bigint from payments where ptype in ('academy_registration', 'academy_enrollment') group by 3
union all
select 5, 'T-REFERENCE THAT ENCODES ITS OWN INSERT TIME - fabricated, not ambiguous', reference || '  |  NGN ' || coalesce(amount::text, '?') || '  |  reference says ' || to_char(minted_at, 'YYYY-MM-DD HH24:MI:SS') || '  |  row says ' || coalesce(to_char(created_at, 'YYYY-MM-DD HH24:MI:SS'), '(undated)') || '  |  ' || case when created_at is null then 'undated row - compare by hand' when abs(extract(epoch from (created_at - minted_at))) <= 600 then 'AGREE to within 10 minutes - minted by our own client' else 'disagree by ' || round(abs(extract(epoch from (created_at - minted_at))) / 60)::text || ' minutes - still a Date.now() shape' end, count(*)::bigint from (select reference, amount, created_at, to_timestamp(substring(reference from 2)::bigint / 1000.0) at time zone 'UTC' as minted_at from (select reference, amount, created_at from payments where reference ~ '^T[0-9]{13}$') guarded) decoded group by reference, amount, created_at, minted_at
) x
order by sort, label;

-- ─────────────────────────────────────────────────────────────────────────────
--  AND THE PEOPLE BEHIND THE FABRICATED ROWS.
--
--  Run separately, once the counts above are understood. Joins the section 1
--  rows to the account holding them, so the question stops being "how many
--  rows" and becomes "who has been let in on one, and for how long".
-- ─────────────────────────────────────────────────────────────────────────────
--
--  SELECT p.reference,
--         p.amount,
--         p.created_at,
--         p.raw_data->>'type'   AS type,
--         p.raw_data->>'status' AS status,
--         u.email,
--         u.roles
--  FROM processed_payments p
--  LEFT JOIN users u ON u.id = p.user_id
--  WHERE p.reference = 'INVALID_REF'
--     OR p.reference LIKE 'E2E\_%'
--     OR p.reference LIKE 'TEST\_E2E\_REF\_%'
--     OR (p.reference LIKE 'T%' AND p.reference !~ '^T[0-9]{15}$')
--  ORDER BY p.created_at;

-- ─────────────────────────────────────────────────────────────────────────────
--  REMOVING THE THREE, IF THAT IS WHAT YOU DECIDE.
--
--  THE GENERAL RULE IS STILL "DO NOT DELETE". A fabricated row may have had
--  something fulfilled against it months ago, and deleting it revokes whatever
--  that was from whoever has been using it. That is a decision about a person.
--
--  THESE THREE ARE THE EXCEPTION, AND ONLY BECAUSE BOTH HALVES ARE PROVEN:
--
--    * fabricated — TEST_E2E_REF_123456 is a test-only shape, and the other
--      two encode their own insert time (section 5), which Paystack cannot do;
--    * and held by test accounts — academyuser02@gmail.com and
--      e2e.user@easysalesexport.com, not customers.
--
--  Neither half alone is enough. A real payer on a fabricated row keeps it.
--
--  WHAT THIS DOES NOT DO: it removes the RECORD OF PAYMENT, not the
--  ENTITLEMENT. `academy_participant` lives on the user document, in roles and
--  serviceRegistrations.academy — deleting the ledger row leaves those test
--  accounts holding Academy access with nothing behind it, which is a
--  different wrong answer than the one you started with. Decide both together.
--
--  RUN THE SELECT FIRST. If it does not return exactly these three rows, stop:
--  something has changed since this was written and the DELETE is not safe.
-- ─────────────────────────────────────────────────────────────────────────────
--
--  SELECT p.reference, p.amount, p.created_at, u.email, u.roles
--  FROM processed_payments p
--  LEFT JOIN users u ON u.id = p.user_id
--  WHERE p.reference IN ('TEST_E2E_REF_123456','T1783690499905','T1783698149704');
--
--  -- Then, with the three confirmed, inside a transaction that refuses to
--  -- commit if the count is not exactly three:
--  BEGIN;
--
--  DELETE FROM processed_payments
--   WHERE reference IN ('TEST_E2E_REF_123456','T1783690499905','T1783698149704');
--
--  -- psql prints "DELETE 3". Anything else and the next line aborts.
--  DO $$
--  DECLARE remaining int;
--  BEGIN
--      SELECT count(*) INTO remaining FROM processed_payments
--       WHERE reference IN ('TEST_E2E_REF_123456','T1783690499905','T1783698149704');
--      IF remaining <> 0 THEN
--          RAISE EXCEPTION 'expected none left, found %', remaining;
--      END IF;
--  END $$;
--
--  COMMIT;   -- or ROLLBACK; if the count surprised you
