-- ============================================================================
-- #848 REGISTRATION FAILED IN PRODUCTION, AND IT FAILED FASTEST FOR THE PEOPLE
--      WHOSE PHONE NUMBER WAS NEW — WHICH IS EVERY GENUINE REGISTRATION.
--
-- From the owner's production log:
--
--     [2026-09-17T08:00:29.746Z] [ERROR] Registration error
--       {"error":"[supabase-db] query users: [57014] canceling statement due to
--        statement timeout", ...
--        at ad.get (/app/.next/server/chunks/76009.js...)}
--
-- The only `users` QUERY in registerAction is the dedup guard, at
-- actions/auth.ts:645 and again at api/auth/register/route.ts:166:
--
--     db.collection(USERS).where("phone", "in", phoneVariants).limit(1).get()
--
-- `phone` is NOT a native column on `users` — the native set is
-- (id, email, roles, created_at, updated_at) — so the adapter emits
--
--     raw_data->>'phone' IN (…)
--
-- and nothing indexed that expression.
--
-- ── WHY `LIMIT 1` DOES NOT SAVE IT, AND WHY THAT IS THE WHOLE FINDING ───────
--
-- LIMIT stops the scan at the first MATCHING row. A duplicate phone is found
-- early and cheaply. A phone nobody has registered before matches nothing, so
-- Postgres reads EVERY row before it can answer "no".
--
-- So the guard is fast for the case it exists to reject and slowest for the
-- case it exists to admit. It does not degrade under load; it degrades under
-- SUCCESS, on a table that grows by one row each time somebody gets through.
-- That is why registration "has always broken in one way or the other": the
-- failure is proportional to the platform's own growth and there is no
-- threshold anybody would have watched for.
--
-- ── 022's HEADER PREDICTED THIS ONE, IN THESE WORDS ─────────────────────────
--
--     "The dedicated tables were given native columns and the expression-index
--      habit did not travel with them."
--
-- #710 fixed `sellerVerificationStatus` (036) and `supabaseAuthId` (033) by
-- exactly this technique, on exactly this table, and `phone` was left. This
-- audit's most repeated finding is a correct rule applied to some of the places
-- it names, and here it is applied to an index habit rather than to code.
--
-- SO THE SWEEP WAS DONE BY FIELD, not by the one site in the log. Every live
-- `users` filter on a phone spelling:
--
--     actions/auth.ts:645                  registration dedup  (the log entry)
--     api/auth/register/route.ts:166       the same guard, API route
--     actions/wave/_wv_applications.ts:203 WAVE duplicate scan
--     actions/admin/_legacy.ts:558         bulk member import, per row
--     lib/cooperative-identity-conflict.ts:88
--     lib/admin-search-helper.ts:60,61     equality, and
--                             :65,66,70,71 RANGE (>= / <) for prefix search
--
-- One btree expression index serves equality, IN and range, so all seven sites
-- are covered by the pair below. `phoneNumber` is the second spelling —
-- _legacy.ts:1124 writes it and admin-search-helper filters it — and it is
-- mostly absent, which makes its index small rather than useless.
--
-- ── MEASURED, ON 50,122 ROWS, LOCAL POSTGRES ────────────────────────────────
--
-- Fixture rows carry a DELIBERATELY SMALL raw_data (three keys). A production
-- user row holds kyc, profile, serviceRegistrations and more, so the scan below
-- reads several times the bytes per row that it does here — which is why this
-- is 12 ms locally and a statement timeout in production. Same caveat as 036,
-- and the fixture rows were deleted after measuring.
--
--   BEFORE — a phone that does NOT exist (every genuine registration)
--     Limit  (actual time=12.783..12.785 rows=0)
--       -> Seq Scan on users
--            Filter: ((raw_data ->> 'phone') = ANY ('{+234…,0803…,…}'))
--            Rows Removed by Filter: 50122
--            Buffers: shared hit=1319
--     Execution Time: 12.809 ms
--
--   AFTER
--     Limit  (actual time=0.022..0.022 rows=0)
--       -> Index Scan using idx_users_phone on users
--            Index Cond: ((raw_data ->> 'phone') = ANY ('{+234…,0803…,…}'))
--            Buffers: shared hit=6 read=2
--     Execution Time: 0.039 ms
--
--   1,319 buffers -> 8.  Per registration attempt.
--
-- ── WHAT THIS DOES NOT CLAIM ────────────────────────────────────────────────
--
-- The same log carries repeated `Error: The destination stream closed early.`
-- (digest 2398141500). That is a render stream ending before it was finished —
-- consistent with a page that took too long, and therefore consistent with a
-- saturated database, but it is NOT shown to be this query and this header
-- should not say it is. If those persist after this index lands, the cause is
-- elsewhere.
--
-- Also measured and deliberately NOT fixed here: lib/module-applicant-count's
-- `total` bucket filters `status IS NOT NULL AND status <> 'not_started'`, and
-- `<>` is not a btree strategy, so an expression index does not serve it — the
-- planner still sequential-scans (3,475 buffers on the same 50k rows). Its four
-- `IN` buckets DO index well (3,475 -> 574). Rewriting the total as an
-- inclusion list would make it indexable and would reintroduce exactly what
-- #824 cost this audit — a list that cannot catch a status nobody has invented
-- yet. Recorded in docs/module-audit-checklist.md §D with the numbers rather
-- than traded away for speed.
--
-- ── HOW TO APPLY ────────────────────────────────────────────────────────────
--
-- Paste into the Supabase SQL Editor, or let it arrive in the consolidated
-- deploy. Plain CREATE INDEX under a lock_timeout, for the reason #469 records
-- in 027's header: CONCURRENTLY cannot run inside a transaction and the SQL
-- Editor always opens one, so a CONCURRENTLY migration here is a migration that
-- never gets applied. The build takes a ShareLock — reads are unaffected,
-- writes pause for the duration — and the lock_timeout turns queueing behind an
-- open transaction into a clean, re-runnable abort.
--
-- Additive only: it creates two indexes and reads, alters and deletes nothing.
-- Safe to re-run: IF NOT EXISTS.
-- ============================================================================

SET lock_timeout = '5s';

CREATE INDEX IF NOT EXISTS idx_users_phone
    ON public.users ((raw_data ->> 'phone'));

CREATE INDEX IF NOT EXISTS idx_users_phone_number
    ON public.users ((raw_data ->> 'phoneNumber'));

RESET lock_timeout;
