-- ============================================================================
-- 051 — THE INDEX EXISTED AND THE QUERY COULD NOT USE IT
--
-- THE OWNER'S PRODUCTION LOG, six of these on one admin dashboard render:
--
--     [DashboardStats] user growth count failed
--       {"month":"Sept 26","error":"[supabase-db] count users: ... HTTP 500"}
--     ... canceling statement due to statement timeout
--
-- The query behind each one is in analytics.service's userGrowthPromise:
--
--     db.collection(USERS).where("createdAt", ">=", start)
--                         .where("createdAt", "<=", end).count()
--
-- ── WHY idx_users_created_at DOES NOT HELP IT ───────────────────────────────
--
-- 027 put `(created_at DESC)` on this table and measured a 430x win for
-- `order by created_at desc limit 20`. That index is real, it is used, and it
-- is IRRELEVANT HERE -- because this query does not touch that column.
--
-- `createdAt` is not in FIELD_TO_COLUMN['users'] and not in
-- NATIVE_COLUMNS['users'] (which lists the snake_case `created_at`), so
-- supabase-db's filter router falls through to applyJsonbFilter and emits
--
--     raw_data->>'createdAt' >= '2026-09-01T00:00:00.000Z'
--
-- A btree on the COLUMN cannot serve a predicate on the JSON KEY. The two
-- names differ by one underscore and one capital letter, and that is the whole
-- distance between a 0.06 ms index scan and a scan of the entire table.
--
-- ── AND THE JSON KEY IS THE RIGHT THING TO FILTER ON, NOT A MISTAKE ─────────
--
-- It would be tempting to map `createdAt` to `created_at` in FIELD_TO_COLUMN
-- instead and let 027's index serve it. That is the wrong fix, and not merely
-- the riskier one: supabase-db's own _mapRow reads
--
--     createdAt: data.raw_data?.createdAt ?? data.created_at
--
-- so the platform treats the JSON key as AUTHORITATIVE and the column as its
-- fallback. Bucketing the chart by the column while every row displays the key
-- would make the two disagree wherever a migrated row carries both -- a
-- quieter defect than the timeout, and a harder one to see.
--
-- ── MEASURED, on 40,000 seeded users in a 107 MB table ──────────────────────
--
-- Production is 42,845 rows / 106 MB, so this is that table's shape. One month
-- bucket, warm cache:
--
--     without   Seq Scan       10,000 buffers   20.9 ms   36,004 rows filtered
--     with      Bitmap Index    1,115 buffers    2.6 ms
--
-- Nine times fewer pages. The dashboard issues SIX of these at once through
-- Promise.all, so the page was reading ~480 MB of heap to draw one line chart,
-- on an instance whose buffer cache is shared with everything else. That is
-- what reaches a statement timeout; the 20.9 ms above is a warm local cache on
-- a dedicated CPU and is the best case, not the reported one.
--
-- THE PLANNER'S ESTIMATE IS THE SECOND FIX. Without the index it guessed
-- rows=200 against an actual 3,996 -- the flat 0.5% default it falls back to
-- for a JSONB expression it has no statistics for. An expression index carries
-- its own statistics, and the estimate became rows=4,065. A 20x
-- underestimate propagates into every join and aggregate above it, so this
-- was not only slow, it was invisible to the planner.
--
-- ── THE NAME, AND THE HAZARD 050 RECORDED ──────────────────────────────────
--
-- `idx_users_raw_created_at`, NOT `idx_users_created_at_json`. 050's header
-- warns that an index name which CONTAINS an existing one makes another test's
-- `toContain` pass for the wrong reason and its `not.toContain` fail for no
-- reason -- that cost a CI cycle on #263. `idx_users_created_at_json` contains
-- `idx_users_created_at` exactly. This name contains none of the nine indexes
-- on `users` and none of them contains it.
--
-- CHANGES NO ROW. Nothing depends on it for correctness -- the query is
-- correct today and merely too slow to finish -- so a deploy landing ahead of
-- this migration is slow rather than broken.
-- ============================================================================

-- Do not queue behind an open transaction and take every writer down with us.
-- 027's note: this converts the one real risk into a clean, re-runnable failure.
SET lock_timeout = '5s';

CREATE INDEX IF NOT EXISTS idx_users_raw_created_at
    ON public.users ((raw_data->>'createdAt'));

RESET lock_timeout;
