/**
 * @jest-environment jsdom
 */

/**
 *   #538 EVERY BADGE IN THE APP POLLED FOREVER, INCLUDING IN TABS NOBODY WAS
 *        LOOKING AT.
 *
 *   Raised by the owner as "the users app is also very slow". It is, and this is
 *   the largest single reason.
 *
 *   Eleven components and hooks hand-rolled the same block — `load()` then
 *   `setInterval(load, 8000)` — and not one asked whether the tab was visible.
 *   A dashboard is a thing people leave open in a background tab, so the app
 *   kept issuing server actions at full rate for as long as the browser stayed
 *   open. Each one re-checks the session, which is a read of the user row
 *   whenever Redis is unset.
 *
 *   MEASURED PER SCREEN, IDLE, DOING NOTHING:
 *
 *     /dashboard   DashboardNav's three pollers (8s, 8s, 10s) plus the page's
 *                  own getMyDashboard (8s, eight queries inside it)
 *                  ≈ 28 server actions and ~75 database queries a minute
 *     /messages    the two nav pollers plus conversations (8s) and messages
 *                  (3s) ≈ 42 server actions a minute
 *     module pages ModuleSidebar (8s), the NotificationCenter inside it (10s)
 *                  and useMembershipStatus (8s) ≈ 21 a minute
 *
 *   AND IT IS THE AUDIT'S USUAL SHAPE UNDERNEATH. getMyDashboard already
 *   returns serviceRegistrations, unreadMessages AND unreadNotifications —
 *   which are exactly the three things DashboardNav polls separately. On
 *   /dashboard all three were fetched twice every eight seconds. That
 *   duplication is recorded here and NOT yet fixed; it needs shared state
 *   between a layout and a page, which is a larger change than this one.
 *
 * ── WHAT IS FIXED ───────────────────────────────────────────────────────────
 *
 *   One primitive, `startVisibilityAwareInterval`, and the `usePolling` hook on
 *   top of it. A hidden tab stops entirely; becoming visible again runs the
 *   task immediately and resumes. So a returning user sees FRESHER data than
 *   before, not staler — previously they saw whatever the last tick left, up to
 *   a full interval old.
 *
 *   Everything moved onto it is a DISPLAY value: an unread count, a badge, a
 *   membership status, a list of registrations. No writes, and nothing
 *   downstream depends on a poll having happened while nobody was looking.
 *
 * ── NOT CLAIMED ─────────────────────────────────────────────────────────────
 *
 *   This does not make the app fast. It removes the load generated by tabs
 *   nobody is looking at, and leaves the foreground rate exactly as it was.
 *   The duplicate-fetch finding above, the 3s message poll, and the fact that
 *   139 of 167 user-facing pages are client components that fetch only after
 *   hydration, are all still open.
 *
 *   MUTATION-TESTED, WITH A CONTROL. Against a green baseline:
 *
 *     the hidden check inverted                        KILLED (8 tests)
 *     the visibilitychange listener never registered   KILLED (1)
 *     the catch-up run on becoming visible removed     KILLED (1)
 *     `immediate: false` ignored                       KILLED (1)
 *     cleanup stops removing the listener              KILLED (1)
 *     one debt-ledger path falsified                   KILLED (3)
 *     the tick's own visibility guard removed          SURVIVED at first —
 *                                                      see below — then KILLED
 *     reword the hook's header                         SURVIVED, as intended
 *
 *   THE SURVIVOR IS THE INTERESTING ONE, AND IT IS RECORDED RATHER THAN
 *   TIDIED AWAY. Deleting the `if (isVisible())` inside the interval tick
 *   changed no result, because every other test reaches the hidden state by
 *   FIRING visibilitychange — which stops the timer by a different route, so
 *   the guard is never the thing under test. The suite was asserting the
 *   listener's behaviour twice and the guard's not at all.
 *
 *   The guard is not redundant: a tab can become hidden without the event
 *   arriving. So the missing test was written rather than the claim softened,
 *   and it is the only one that hides the tab WITHOUT dispatching.
 */

import { describe, it, expect, beforeEach, afterEach, jest } from '@jest/globals';
import { readFileSync, readdirSync, statSync, existsSync } from 'fs';
import { join } from 'path';
import { renderHook } from '@testing-library/react';
import { stripComments } from '@/lib/testing/strip-comments';
import { usePolling, startVisibilityAwareInterval } from '@/hooks/usePolling';

const ROOT = process.cwd();

/**
 * jsdom reports visibilityState from the document, and it is not writable by
 * assignment, so it is redefined. Firing the event separately is deliberate:
 * the production bug is precisely that nothing LISTENED, so a test that only
 * flipped the value would pass against the unfixed code.
 */
function setVisibility(state: 'visible' | 'hidden'): void {
    Object.defineProperty(document, 'visibilityState', {
        configurable: true,
        get: () => state,
    });
    document.dispatchEvent(new Event('visibilitychange'));
}

beforeEach(() => {
    jest.useFakeTimers();
    setVisibility('visible');
});

afterEach(() => {
    jest.useRealTimers();
});

// ─────────────────────────────────────────────────────────────────────────────
describe('#538 — the primitive', () => {
    it('POLLS WHILE THE TAB IS VISIBLE', () => {
        const task = jest.fn<() => void>();
        const stop = startVisibilityAwareInterval(task, 1000);

        expect(task).toHaveBeenCalledTimes(1);   // the immediate run
        jest.advanceTimersByTime(3000);
        expect(task).toHaveBeenCalledTimes(4);

        stop();
    });

    it('AND STOPS COMPLETELY ONCE THE TAB IS HIDDEN', () => {
        //   THE test. Before the fix this kept counting.
        const task = jest.fn<() => void>();
        const stop = startVisibilityAwareInterval(task, 1000);
        task.mockClear();

        setVisibility('hidden');
        jest.advanceTimersByTime(60_000);

        expect(task).not.toHaveBeenCalled();
        stop();
    });

    it('AND CATCHES UP THE MOMENT IT IS LOOKED AT AGAIN', () => {
        //   A pause that did not catch up would show a badge up to one whole
        //   interval stale on return — worse than the behaviour it replaces.
        const task = jest.fn<() => void>();
        const stop = startVisibilityAwareInterval(task, 10_000);
        setVisibility('hidden');
        jest.advanceTimersByTime(60_000);
        task.mockClear();

        setVisibility('visible');

        expect(task).toHaveBeenCalledTimes(1);
        stop();
    });

    it('AND RESUMES THE INTERVAL, NOT JUST THE ONE CATCH-UP', () => {
        //   The vacuity guard: a fix that caught up once and never restarted
        //   the timer passes the test above and silently freezes every badge.
        const task = jest.fn<() => void>();
        const stop = startVisibilityAwareInterval(task, 1000);
        setVisibility('hidden');
        jest.advanceTimersByTime(5000);
        setVisibility('visible');
        task.mockClear();

        jest.advanceTimersByTime(3000);

        expect(task).toHaveBeenCalledTimes(3);
        stop();
    });

    it('AND HONOURS immediate:false for a caller that already loaded once', () => {
        //   /dashboard kicks off its own first load, so running here as well
        //   would double every mount of the most expensive poller in the app.
        const task = jest.fn<() => void>();
        const stop = startVisibilityAwareInterval(task, 1000, { immediate: false });

        expect(task).not.toHaveBeenCalled();
        jest.advanceTimersByTime(1000);
        expect(task).toHaveBeenCalledTimes(1);

        stop();
    });

    it('AND STOPS EVEN IF THE BROWSER NEVER FIRES visibilitychange', () => {
        //   The belt-and-braces guard inside the tick, which exists because a
        //   tab can become hidden without the event arriving — a browser that
        //   throttles a background tab rather than dispatching, or an event
        //   swallowed while the page was mid-navigation.
        //
        //   THIS TEST WAS MISSING AND THE MUTANT SURVIVED. Deleting the guard
        //   changed no result, because every other test reaches hidden state by
        //   firing the event, which stops the timer by another route. So the
        //   only assertion that could ever distinguish them is this one: hide
        //   the tab WITHOUT telling anybody.
        const task = jest.fn<() => void>();
        const stop = startVisibilityAwareInterval(task, 1000);
        task.mockClear();

        Object.defineProperty(document, 'visibilityState', {
            configurable: true,
            get: () => 'hidden',
        });
        // Deliberately NO dispatchEvent here.
        jest.advanceTimersByTime(30_000);

        expect(task).not.toHaveBeenCalled();
        stop();
    });

    it('AND STOPS FOR GOOD WHEN CLEANED UP, LISTENER INCLUDED', () => {
        //   A cleanup that cleared the timer but left the listener attached
        //   would resurrect a dead component's poll on the next tab focus.
        const task = jest.fn<() => void>();
        const stop = startVisibilityAwareInterval(task, 1000);
        stop();
        task.mockClear();

        jest.advanceTimersByTime(10_000);
        setVisibility('hidden');
        setVisibility('visible');
        jest.advanceTimersByTime(10_000);

        expect(task).not.toHaveBeenCalled();
    });
});

// ─────────────────────────────────────────────────────────────────────────────
describe('#538 — the hook', () => {
    it('does nothing at all while disabled', () => {
        //   Every caller passes `enabled: !!userId`. A signed-out visitor must
        //   not poll a session-scoped action at all.
        const task = jest.fn<() => void>();
        renderHook(() => usePolling(task, 1000, { enabled: false }));

        jest.advanceTimersByTime(10_000);
        expect(task).not.toHaveBeenCalled();
    });

    it('polls while enabled, and pauses with the tab', () => {
        const task = jest.fn<() => void>();
        renderHook(() => usePolling(task, 1000));

        jest.advanceTimersByTime(2000);
        const whileVisible = task.mock.calls.length;
        expect(whileVisible).toBeGreaterThan(1);

        setVisibility('hidden');
        jest.advanceTimersByTime(30_000);

        expect(task).toHaveBeenCalledTimes(whileVisible);
    });

    it('calls the LATEST closure, not the one from the first render', () => {
        //   The reason the task lives in a ref. If the interval captured the
        //   first render's closure, a badge would keep writing to stale state.
        const first = jest.fn<() => void>();
        const second = jest.fn<() => void>();
        const { rerender } = renderHook(
            ({ fn }: { fn: () => void }) => usePolling(fn, 1000),
            { initialProps: { fn: first } },
        );
        first.mockClear();

        rerender({ fn: second });
        jest.advanceTimersByTime(2000);

        expect(second).toHaveBeenCalled();
        expect(first).not.toHaveBeenCalled();
    });

    it('RESTARTS AND REFETCHES WHEN THE IDENTITY CHANGES', () => {
        //   The counterpart to the test below. The poll must NOT restart on
        //   every render, but it MUST restart when the thing being polled
        //   about changes — the signed-in user, the module being asked about.
        //
        //   THIS WAS A REGRESSION I INTRODUCED AND #416'S SUITE CAUGHT IT. The
        //   first version keyed the effect on the interval alone, so after a
        //   user change the timer survived and the badge went on showing the
        //   PREVIOUS user's count until the next tick.
        const task = jest.fn<() => void>();
        const { rerender } = renderHook(
            ({ id }: { id: string }) => usePolling(task, 10_000, { restartKey: id }),
            { initialProps: { id: 'user-1' } },
        );
        task.mockClear();

        rerender({ id: 'user-2' });

        expect(task).toHaveBeenCalledTimes(1);
    });

    it('does NOT restart the interval on every render', () => {
        //   If the task were in the dependency array, each poll would set state,
        //   re-render, and rebuild the timer — so the true period would drift
        //   and, with a fast enough render, never fire at all.
        const task = jest.fn<() => void>();
        const { rerender } = renderHook(() => usePolling(task, 1000));
        task.mockClear();

        for (let i = 0; i < 5; i++) {
            rerender();
            jest.advanceTimersByTime(200);
        }

        //   1000ms of total elapsed time across five renders = exactly one tick.
        expect(task).toHaveBeenCalledTimes(1);
    });
});

// ─────────────────────────────────────────────────────────────────────────────
describe('#538 — no poller goes back to a bare setInterval', () => {
    /**
     * Polling sites that are NOT server round-trips, and so have no reason to
     * pause: animation and countdown timers driven entirely in the browser, a
     * camera scan loop, a session-timeout clock that must keep counting while
     * the tab is hidden precisely because that is when a session lapses.
     *
     * Named rather than pattern-matched, so adding one is a deliberate act.
     */
    const NOT_SERVER_POLLS = new Set([
        'src/components/ui/ImageSlider.tsx',
        'src/components/features/HeroSlider.tsx',
        'src/components/hub/HubHero.tsx',
        'src/components/hub/PlatformStats.tsx',
        'src/components/CountdownTimer.tsx',
        'src/components/auth/SessionActivityTracker.tsx',
        'src/components/DeploymentWatcher.tsx',
        'src/components/lms/VideoPlayer.tsx',
        'src/hooks/usePolling.ts',
        'src/app/verify-id/page.tsx',
        'src/app/wave/landing/page.tsx',
        'src/app/cooperatives/payment/callback/page.tsx',
        'src/app/academy/[courseId]/quiz/[moduleId]/page.tsx',
    ]);

    /**
     * The sites that DO fetch from the server on a timer and have not been
     * moved onto the shared primitive yet.
     *
     * This list is a DEBT LEDGER, not permission. Each one still polls a
     * background tab; they are listed so the number is visible and can only go
     * down — adding to it is a deliberate act, and the test below proves the
     * sweep can still fail.
     */
    const STILL_HAND_ROLLED = new Set([
        'src/app/messages/page.tsx',
        'src/app/escrow/[id]/chat/page.tsx',
        'src/app/dashboard/disputes/page.tsx',
        'src/app/dashboard/notifications/page.tsx',
        'src/app/wave/(member)/live-training/page.tsx',
        //   Admin screens. Same defect, smaller blast radius — a handful of
        //   staff rather than every member — so they are recorded and left for
        //   the admin pass rather than changed in a user-facing fix.
        'src/app/admin/messages/page.tsx',
        'src/app/admin/academy/live/[courseId]/page.tsx',
        'src/app/admin/wave/training/live/[eventId]/page.tsx',
    ]);

    function filesWithBareInterval(): string[] {
        const found: string[] = [];
        const walk = (dir: string) => {
            for (const e of readdirSync(dir)) {
                const full = join(dir, e);
                if (statSync(full).isDirectory()) {
                    if (e !== '__tests__' && e !== 'node_modules') walk(full);
                } else if (/\.tsx?$/.test(e)) {
                    const src = stripComments(readFileSync(full, 'utf-8'), { label: full });
                    if (/setInterval\s*\(/.test(src)) found.push(full.slice(ROOT.length + 1));
                }
            }
        };
        walk(join(ROOT, 'src'));
        return found.sort();
    }

    it('THE SIX ALWAYS-MOUNTED POLLERS USE THE SHARED PRIMITIVE', () => {
        //   These are the ones every signed-in user pays for on every screen.
        const CONVERTED = [
            'src/components/dashboard/DashboardNav.tsx',
            'src/components/layout/ModuleSidebar.tsx',
            'src/components/layout/NotificationCenter.tsx',
            'src/components/layout/Sidebar.tsx',
            'src/hooks/useMembershipStatus.ts',
            'src/hooks/useUnreadNotifications.ts',
        ];
        for (const f of CONVERTED) {
            const src = stripComments(readFileSync(join(ROOT, f), 'utf-8'), { label: f });
            expect({ f, usesHook: /usePolling\s*\(/.test(src) }).toEqual({ f, usesHook: true });
            expect({ f, bareInterval: /setInterval\s*\(/.test(src) }).toEqual({ f, bareInterval: false });
        }
    });

    it('AND THE DASHBOARD PAGE — the most expensive one — USES THE PRIMITIVE', () => {
        const src = stripComments(
            readFileSync(join(ROOT, 'src/app/dashboard/page.tsx'), 'utf-8'),
            { label: 'dashboard' },
        );
        expect(src).toContain('startVisibilityAwareInterval(');
        expect(/setInterval\s*\(/.test(src)).toBe(false);
    });

    it('AND NO NEW HAND-ROLLED POLLER HAS APPEARED', () => {
        const unaccounted = filesWithBareInterval()
            .filter(f => !NOT_SERVER_POLLS.has(f) && !STILL_HAND_ROLLED.has(f));

        expect(unaccounted).toEqual([]);
    });

    it('AND THE SWEEP CAN STILL FAIL — every listed file exists', () => {
        //   #484's shape: a list of paths that no longer exist would silence the
        //   sweep while reading as deliberate.
        for (const f of [...NOT_SERVER_POLLS, ...STILL_HAND_ROLLED]) {
            expect({ f, exists: existsSync(join(ROOT, f)) }).toEqual({ f, exists: true });
        }
    });

    it('AND THE DEBT LEDGER IS HONEST — each listed file really does poll', () => {
        //   A file parked in STILL_HAND_ROLLED that no longer has a setInterval
        //   is debt that was quietly paid; it should leave the list, not sit on
        //   it looking like outstanding work.
        const actuallyPolling = new Set(filesWithBareInterval());
        for (const f of STILL_HAND_ROLLED) {
            expect({ f, polls: actuallyPolling.has(f) }).toEqual({ f, polls: true });
        }
    });
});
